name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-express-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-express-app:latest

      # Step 4: SSH into EC2 and deploy the Docker container
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Stop and remove any running container named 'app'
            docker stop app || true
            docker rm app || true

            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-express-app:latest

            # Run the Docker container
            docker run -d --name app -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/cicd-express-app:latest
